# Generated by Django 6.1.1 on 2026-09-28 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_hours', models.PositiveIntegerField()),
                ('photo_count', models.PositiveIntegerField()),
                ('extra_photos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('Wedding', 'زواج'), ('Corporate Event', 'فعالية شركات'), ('Brand Event', 'فعالية علامة تجارية'), ('Other', 'أخرى')], max_length=30)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Confirmed', 'مؤكد'), ('Cancelled', 'ملغي')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.package')),
            ],
        ),
    ]
