# Generated by Django 6.1.1 on 2026-09-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'زواج'), ('Graduation', 'تخرج'), ('Corporate Event', 'فعالية شركات'), ('Brand Event', 'فعالية علامة تجارية'), ('Other', 'أخرى')], max_length=30),
        ),
    ]
